// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzqytytnntyblnxpkrks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6cXl0eXRubnR5YmxueHBrcmtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2MTY2ODgsImV4cCI6MjA3NjE5MjY4OH0.TXNsrjbOYyA2eeeJTfaisrzHFVm1Fzv9KuE3hCugCxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});